# Generated by Django 3.1.5 on 2021-04-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('timestamp1', models.DateTimeField(auto_now_add=True)),
                ('author1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author_messages1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
